source: src
paths:
  uploads: assets/uploads/:title
  static: ''
data_config:
  banner:
    path: _data/banner.yml
  docCollections:
    path: _data/docCollections.json
  site:
    path: _data/site.json
  theme:
    path: _data/theme.json
collections_config_override: true
collections_config:
  data:
    path: _data
    icon: settings
    disable_url: true
    disable_add: true 
    disable_add_folder: true 
    disable_file_actions: true 
  docs:
    path: docs
    output: true
    glob:
      - '!robots.njk'
      - '!sitemap.njk'
      - '!404.md'
      - '!docs.json'
    name: Docs
    description: All your docs
    icon: description
    documentation: null
    preview:
      gallery: description
    sort: null
    sort_options: null
    singular_name: null
    singular_key: null
    _editables: null
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      removeFromNavigation:
        type: switch
        label: Remove from navigation
        comment: 
      eleventyExcludeFromCollections:
        type: switch
        label: Exclude from collections
        comment: Exclude this page from collections, this wont show up in navigation or sitemap
      eleventyNavigation:
        label: Navigation
      eleventyNavigation.key:
        comment: How this page is identified in the navigation
      eleventyNavigation.order:
        comment: What order in the navigation
      eleventyNavigation.title:
        label: Display Title
        comment: >-
          What website visitors will see. Leave blank if you want to use the key
          as Display Title
      eleventyNavigation.parent:
        comment: What key this should be grouped with. Leave blank for no grouping
      eleventyNavigation.url:
        label: External Link
        comment: >-
          If you want to have a link to another website or file on your site,
          place that link here. Leave blank for all other situations. WARNING:
          this will prevent this page from building and showing up in your
          website.
      pageLink:
        label: Page Location
        comment: The location of this page on your webiste i.e. Example.com/mylocation. Leave blank if you want to just use the page title as the page location.
        type: text
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      permalink:
        hidden: true
      pagination:
        hidden: true
      layout:
        hidden: true
      tags:
        type: select
        options:
          values: data.docCollections[*].key
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas:
      default:
        path: .cloudcannon/schemas/doc.md
    schema_key: null
_inputs:
  markdownContent:
    type: markdown
    options:
      link: true
      blockquote: true
      bold: true
      format: p h2 h3 h4 h5 h6
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      numberedlist: true
      indent: false
      outdent: false
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      snippet: true
  description:
    type: markdown
    options:
      link: true
      bold: true
      italic: true
      undo: true
      redo: true
      initial_height: 135
  socialImage:
    type: image
    hidden: false
  id:
    hidden: true
    instance_value: UUID
  heading_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) 
    type: text
  content_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) 
      available
    type: text 
  logo_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) 
    type: text 
  showNote:
    type: switch
    comment: >-
      Hide/Show the note that contains helpful information about the live
      editing of this component. This note doesn't show up on the live site.
  icon:
    comment: >-
      Visit [https://heroicons.com/](https://heroicons.com/) to see the full
      library
    type: select
    options:
      values:
        - academic-cap
        - adjustments-horizontal
        - adjustments-vertical
        - archive-box-arrow-down
        - archive-box-x-mark
        - archive-box
        - arrow-down-circle
        - arrow-down-left
        - arrow-down-on-square-stack
        - arrow-down-on-square
        - arrow-down-right
        - arrow-down-tray
        - arrow-down
        - arrow-left-circle
        - arrow-left-on-rectangle
        - arrow-left
        - arrow-long-down
        - arrow-long-left
        - arrow-long-right
        - arrow-long-up
        - arrow-path-rounded-square
        - arrow-path
        - arrow-right-circle
        - arrow-right-on-rectangle
        - arrow-right
        - arrow-small-down
        - arrow-small-left
        - arrow-small-right
        - arrow-small-up
        - arrow-top-right-on-square
        - arrow-trending-down
        - arrow-trending-up
        - arrow-up-circle
        - arrow-up-left
        - arrow-up-on-square-stack
        - arrow-up-on-square
        - arrow-up-right
        - arrow-up-tray
        - arrow-up
        - arrow-uturn-down
        - arrow-uturn-left
        - arrow-uturn-right
        - arrow-uturn-up
        - arrows-pointing-in
        - arrows-pointing-out
        - arrows-right-left
        - arrows-up-down
        - at-symbol
        - backspace
        - backward
        - banknotes
        - bars-2
        - bars-3-bottom-left
        - bars-3-bottom-right
        - bars-3-center-left
        - bars-3
        - bars-4
        - bars-arrow-down
        - bars-arrow-up
        - battery-0
        - battery-100
        - battery-50
        - beaker
        - bell-alert
        - bell-slash
        - bell-snooze
        - bell
        - bolt-slash
        - bolt
        - book-open
        - bookmark-slash
        - bookmark-square
        - bookmark
        - briefcase
        - bug-ant
        - building-library
        - building-office-2
        - building-office
        - building-storefront
        - cake
        - calculator
        - calendar-days
        - calendar
        - camera
        - chart-bar-square
        - chart-bar
        - chart-pie
        - chat-bubble-bottom-center-text
        - chat-bubble-bottom-center
        - chat-bubble-left-ellipsis
        - chat-bubble-left-right
        - chat-bubble-left
        - chat-bubble-oval-left-ellipsis
        - chat-bubble-oval-left
        - check-badge
        - check-circle
        - check
        - chevron-double-down
        - chevron-double-left
        - chevron-double-right
        - chevron-double-up
        - chevron-down
        - chevron-left
        - chevron-right
        - chevron-up-down
        - chevron-up
        - circle-stack
        - clipboard-document-check
        - clipboard-document-list
        - clipboard-document
        - clipboard
        - clock
        - cloud-arrow-down
        - cloud-arrow-up
        - cloud
        - code-bracket-square
        - code-bracket
        - cog-6-tooth
        - cog-8-tooth
        - cog
        - command-line
        - computer-desktop
        - cpu-chip
        - credit-card
        - cube-transparent
        - cube
        - currency-bangladeshi
        - currency-dollar
        - currency-euro
        - currency-pound
        - currency-rupee
        - currency-yen
        - cursor-arrow-rays
        - cursor-arrow-ripple
        - device-phone-mobile
        - device-tablet
        - document-arrow-down
        - document-arrow-up
        - document-chart-bar
        - document-check
        - document-duplicate
        - document-magnifying-glass
        - document-minus
        - document-plus
        - document-text
        - document
        - ellipsis-horizontal-circle
        - ellipsis-horizontal
        - ellipsis-vertical
        - envelope-open
        - envelope
        - exclamation-circle
        - exclamation-triangle
        - eye-dropper
        - eye-slash
        - eye
        - face-frown
        - face-smile
        - film
        - finger-print
        - fire
        - flag
        - folder-arrow-down
        - folder-minus
        - folder-open
        - folder-plus
        - folder
        - forward
        - funnel
        - gif
        - gift-top
        - gift
        - globe-alt
        - globe-americas
        - globe-asia-australia
        - globe-europe-africa
        - hand-raised
        - hand-thumb-down
        - hand-thumb-up
        - hashtag
        - heart
        - home-modern
        - home
        - identification
        - inbox-arrow-down
        - inbox-stack
        - inbox
        - information-circle
        - key
        - language
        - lifebuoy
        - light-bulb
        - link
        - list-bullet
        - lock-closed
        - lock-open
        - magnifying-glass-circle
        - magnifying-glass-minus
        - magnifying-glass-plus
        - magnifying-glass
        - map-pin
        - map
        - megaphone
        - microphone
        - minus-circle
        - minus-small
        - minus
        - moon
        - musical-note
        - newspaper
        - no-symbol
        - paint-brush
        - paper-airplane
        - paper-clip
        - pause-circle
        - pause
        - pencil-square
        - pencil
        - phone-arrow-down-left
        - phone-arrow-up-right
        - phone-x-mark
        - phone
        - photo
        - play-circle
        - play-pause
        - play
        - plus-circle
        - plus-small
        - plus
        - power
        - presentation-chart-bar
        - presentation-chart-line
        - printer
        - puzzle-piece
        - qr-code
        - question-mark-circle
        - queue-list
        - radio
        - receipt-percent
        - receipt-refund
        - rectangle-group
        - rectangle-stack
        - rocket-launch
        - rss
        - scale
        - scissors
        - server-stack
        - server
        - share
        - shield-check
        - shield-exclamation
        - shopping-bag
        - shopping-cart
        - signal-slash
        - signal
        - sparkles
        - speaker-wave
        - speaker-x-mark
        - square-2-stack
        - square-3-stack-3d
        - squares-2x2
        - squares-plus
        - star
        - stop-circle
        - stop
        - sun
        - swatch
        - table-cells
        - tag
        - ticket
        - trash
        - trophy
        - truck
        - tv
        - user-circle
        - user-group
        - user-minus
        - user-plus
        - user
        - users
        - variable
        - video-camera-slash
        - video-camera
        - view-columns
        - viewfinder-circle
        - wallet
        - wifi
        - window
        - wrench-screwdriver
        - wrench
        - x-circle
        - x-mark
_snippets:
  videoEmbed:
    template: eleventy_liquid_bookshop_component
    inline: false
    preview:
      text: Youtube or Vimeo
    definitions:
      component_name: snippets/videoEmbed
      named_args:
        - editor_key: platform
          type: string
        - editor_key: videoId
          type: string
    _inputs:
      videoId:
        comment: "You can find this in the URL of the video you want to embed. For example, https://www.youtube.com/watch?v=YOUR_VIDEO_ID, or for vimeo https://vimeo.com/YOUR_VIDEO_ID"
      platform:
        comment: "Youtube or Vimeo"
        type: choice
        options:
          allow_empty: false
          value_key: id
          values:
            - id: youtube
              name: Youtube
            - id: vimeo
              name: Vimeo
  styledText:
    template: eleventy_liquid_bookshop_component
    inline: true
    preview:
      text: Styled Text
    definitions:
      component_name: generic/styledText
      named_args:
        - editor_key: text
          type: string
        - editor_key: style
          type: string
    _inputs:
      style:
        comment: "The style of the text"
        type: select
        options:
          value_key: id
          values:
            - id: green label
              name: Green Label
            - id: red label
              name: Red Label
            - id: blue label
              name: Blue Label
            - id: kbd
              name: Keyboard
_select_data: {}
_structures:
  content_blocks:
    style: modal
  editorial_blocks:
    style: modal
_editables:
  content:
    link: true
    blockquote: true
    bold: true
    format: p h2 h3 h4 h5 h6
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    numberedlist: true
    indent: false
    outdent: false
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    snippet: true
    allow_custom_markup: false

timezone: Etc/UTC