# Metadata about this component, to be used in the CMS
spec:
  structures:
    - editorial_blocks
  label: "Tabs"
  description:
  icon: tabs
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  tabs:
    - title: 
      editorials: [bookshop:structure:editorial_blocks!(generic/textBlock)]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    comment: 'The title of the tab'
    label: 'Tab title'
