# Metadata about this component, to be used in the CMS
spec:
  structures:
    - editorial_blocks
  label: "MermaidGraph"
  description:
  icon: add_chart
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  mermaidCode: >-
    graph TD;

    A[Want graphs in 11ty] -->|Search Plugin| B(Found plugin);

    B --> C{Use plugin?};

    C -->|Yes| D[NICE GRAPHS];

    C -->|No| E[NO GRAPHS];


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  mermaidCode:
    type: code
