// A Node.js script to build SCSS variables from a JSON theme file.
//
// To run this script:
// 1. Make sure you have Node.js installed.
// 2. Save this file as `build-theme.js` in your project's root directory.
// 3. Run it from your terminal using: `node build-theme.js`

const fs = require('fs');
const path = require('path');

// Define the input and output file paths.
const themeJsonPath = path.join(process.cwd(), 'src', '_data', 'theme.json');
const outputScssPath = path.join(process.cwd(), 'src', 'assets', 'styles', 'variables.scss');

/**
 * Converts a JSON object of theme styles into a string of CSS custom properties.
 * @param {object} themeObject - The object containing style key-value pairs.
 * @returns {string} A formatted string of CSS variables.
 */
function generateCssVariables(themeObject) {
  // Indent each line for better readability in the output SCSS file.
  const indent = '  ';
  
  // Use Object.entries to iterate over the key-value pairs and map them to CSS variable declarations.
  return Object.entries(themeObject)
    .map(([key, value]) => {
      // Convert snake_case keys (like 'heading_font') to kebab-case (--heading-font)
      const cssVarName = key.replace(/_/g, '-');
      return `${indent}--${cssVarName}: ${value};`;
    })
    .join('\n');
}

/**
 * Main function to read the theme JSON and generate the SCSS variables file.
 */
function buildThemeStyles() {
  try {
    // --- 1. Read and Parse the JSON File ---
    console.log(`Reading theme file from: ${themeJsonPath}`);
    const themeFileContent = fs.readFileSync(themeJsonPath, 'utf8');
    const theme = JSON.parse(themeFileContent);

    if (!theme.light || !theme.dark) {
      throw new Error('Theme JSON must contain both "light" and "dark" theme objects.');
    }

    // --- 2. Separate Color Themes from Other Root Properties (like fonts) ---
    const { light, dark, ...rootProperties } = theme;

    // --- 3. Generate CSS Variable Blocks ---
    const lightVars = generateCssVariables(light);
    const darkVars = generateCssVariables(dark);
    const rootVars = generateCssVariables(rootProperties); // This will handle fonts and any other global vars

    // --- 4. Assemble the Final SCSS Content ---
    const scssContent = `
// ====================================================================
// THIS FILE IS AUTOMATICALLY GENERATED BY THE 'build-theme.js' SCRIPT
// DO NOT EDIT THIS FILE DIRECTLY.
//
// Your theme styles are defined in 'src/_data/theme.json'.
// Run 'node build-theme.js' to regenerate this file.
// ====================================================================

:root {
${lightVars}
${rootVars ? `\n${rootVars}` : ''}
}

.dark {
${darkVars}
}
`;

    // --- 5. Write the SCSS File ---
    fs.mkdirSync(path.dirname(outputScssPath), { recursive: true });
    fs.writeFileSync(outputScssPath, scssContent.trim());
    
    console.log(`✅ SCSS variables successfully generated at: ${outputScssPath}`);

  } catch (error) {
    console.error('❌ Error generating theme styles:', error);
    process.exit(1); // Exit with an error code
  }
}

// Run the script.
buildThemeStyles();
