// A Node.js script to build SCSS variables from a JSON theme file.
//
// To run this script:
// 1. Make sure you have Node.js installed.
// 2. Save this file as `build-theme.js` in your project's root directory.
// 3. Run it from your terminal using: `node build-theme.js`

const fs = require('fs');
const path = require('path');

// Define the input and output file paths.
const themeJsonPath = path.join(__dirname, 'src', '_data', 'theme.json');
const outputScssPath = path.join(__dirname, 'src', 'assets', 'styles', 'variables.scss');

/**
 * Converts a JSON object of theme colors into a string of CSS custom properties.
 * @param {object} themeObject - The object containing color key-value pairs (e.g., { "background-body": "#ffffff" }).
 * @returns {string} A formatted string of CSS variables.
 */
function generateCssVariables(themeObject) {
  // Indent each line for better readability in the output SCSS file.
  const indent = '  ';
  
  // Use Object.entries to iterate over the key-value pairs and map them to CSS variable declarations.
  return Object.entries(themeObject)
    .map(([key, value]) => `${indent}--${key}: ${value};`)
    .join('\n');
}

/**
 * Main function to read the theme JSON and generate the SCSS variables file.
 */
function buildThemeStyles() {
  try {
    // --- 1. Read and Parse the JSON File ---
    console.log(`Reading theme file from: ${themeJsonPath}`);
    const themeFileContent = fs.readFileSync(themeJsonPath, 'utf8');
    const theme = JSON.parse(themeFileContent);

    if (!theme.light || !theme.dark) {
      throw new Error('Theme JSON must contain both "light" and "dark" theme objects.');
    }

    // --- 2. Generate CSS Variable Blocks ---
    const lightVars = generateCssVariables(theme.light);
    const darkVars = generateCssVariables(theme.dark);

    // --- 3. Assemble the Final SCSS Content ---
    // This structure ensures that the light theme variables are the default (`:root`),
    // and the dark theme variables are applied when the `.dark` class is present on a parent element.
    const scssContent = `
// ====================================================================
// THIS FILE IS AUTOMATICALLY GENERATED BY THE 'build-theme.js' SCRIPT
// DO NOT EDIT THIS FILE DIRECTLY.
//
// Your theme colors are defined in 'src/_data/theme.json'.
// Run 'node build-theme.js' to regenerate this file.
// ====================================================================

:root {
${lightVars}
}

.dark {
${darkVars}
}
`;

    // --- 4. Write the SCSS File ---
    // Ensure the output directory exists before writing the file.
    fs.mkdirSync(path.dirname(outputScssPath), { recursive: true });
    fs.writeFileSync(outputScssPath, scssContent.trim());
    
    console.log(`✅ SCSS variables successfully generated at: ${outputScssPath}`);

  } catch (error) {
    console.error('❌ Error generating theme styles:', error);
    process.exit(1); // Exit with an error code
  }
}

// Run the script.
buildThemeStyles();
